### PR TITLE
IHO-S44 corrections

### PR DESCRIPTION
**Pull request by anermina**
I have a several questions regarding IHO-S44:
- This document also includes a draft number: 6th edition, draft 2.0.0. Maybe we should add draft number in document attributes?
- I'm not sure whether IHO prefers using definition lists for the terms, instead of separate subsections. In order to avoid double-correcting the document, I didn't change the form here. Please let me know whether to use separate subsections, or definition lists for the terms in IHO.
- Following page is missing at the end of the converted document. Please let me know if I should add it.
image

Note:
- I wasn't sure whether draft version 2.0.0 was used (it was, confirmed later), so I added separately in #39 one page which was missing in section 7.6.

### CODE REVIEW

**Comment by ronaldtse** [comment]
> This document also includes a draft number: 6th edition, draft 2.0.0. Maybe we should add draft number in document attributes?

I think this is best expressed as ":edition: 6, ":version: 2.0.0" and ":draft:", but the "draft" attribute here is most certainly not needed since it isn't a draft.

> I'm not sure whether IHO prefers using definition lists for the terms, instead of separate subsections. In order to avoid double-correcting the document, I didn't change the form here. Please let me know whether to use separate subsections, or definition lists for the terms in IHO.

We need to use the "subsection" syntax for all "terms and definitions".

**Comment by ronaldtse** [comment]
> Following page is missing at the end of the converted document. Please let me know if I should add it.

Yes please! Thanks!

**Comment by manuelfuenmayor** [comment]
>I think this is best expressed as ":edition: 6, ":version: 2.0.0" and ":draft:", but the "draft" attribute here is most certainly not needed since it isn't a draft.

Changes applied.

> > Following page is missing at the end of the converted document. Please let me know if I should add it.
> 
> Yes please! Thanks!

Page added.

**Comment by manuelfuenmayor** [comment]
Also, I took the liberty of adding the missing part that @anermina reported and pushed in https://github.com/metanorma/mn-samples-iho/pull/39

**Pull request merged**
