### PR TITLE
Add IHO S-102

### PR DESCRIPTION
**Pull request by manuelfuenmayor**
As requested in https://github.com/metanorma/mn-samples-iho/issues/3

*Comments:*
* Several bibliography entries that weren't in "References" section (but are referenced in the content) were included.
* IHO references were not recognized by relaton.
* Six level subsections were typeset in boldfaced as they’re not supported by Metanorma nor Asciidoctor.
* Landscape mode was used and it works very well (thanks @opoudjis ), with one caveat though: it introduces a blank page after getting back to portrait mode.
* New bug found: https://github.com/metanorma/metanorma-standoc/issues/239

Thanks!

### CODE REVIEW

**Comment by ronaldtse** [comment]
> Six level subsections were typeset in boldfaced as they’re not supported by Metanorma nor Asciidoctor. 

@manuel489 this is not true; Metanorma supports beyond six levels of subsections.

**Review by ronaldtse — CHANGES_REQUESTED** [review]
> Six level subsections were typeset in boldfaced as they’re not supported by Metanorma nor Asciidoctor.

They are supported. Please change these boldfaced entries to appropriate section symbols. Thanks.

**Comment by manuelfuenmayor** [comment]
@ronaldtse , I have made a test, and it seems not to be supported.

*Original source:*
original-cap

*Code:*

````
======= minimumDepth

The attribute _minimumDepth_ has the value type _Real_ and describes the lower bound of the depth estimate for all the _depth_ values in *S102_BathymetryValues* record. This attribute is required. There is no default.

======= maximumDepth

The attribute _maximumDepth_ has the value type _Real_ and describes the upper bound of the depth estimate for all the depth values in *S102_BathymetryValues* record. This attribute is required. There is no default.

======= minimumDisplayScale

The larger value of the ratio of the linear dimensions of the features of a dataset presented in the display and the actual dimensions of the features represented (largest scale) of the scale range of the dataset. A list of display scale ranges is available in <<tab-informative-grid-resolution-and-resulting-tile-size-at-chart-scale>>, 1st column.
````

*DOC output:*
doc-cap

(By "six level sections", I mean "six number sections" in output.)

Thanks!

**Comment by ronaldtse** [comment]
> I have made a test, and it seems not to be supported.

@manuel489 this is a bug, it was implemented before. Please file in metanorma-standoc. Thanks!

**Comment by ronaldtse** [comment]
@manuel489 can you have update the section titles and we'll merge it first? Thanks

**Comment by manuelfuenmayor** [comment]
> @manuel489 can you have update the section titles and we'll merge it first? Thanks

@ronaldtse , ok done. 
So, I'm going to open the ticket...

Thanks!

**Comment by manuelfuenmayor** [comment]
> @manuel489 this is a bug, it was implemented before. Please file in metanorma-standoc. Thanks!

Ticket: https://github.com/metanorma/metanorma-standoc/issues/240

**Comment by ronaldtse** [comment]
Thank you @manuel489 !

**Comment by ronaldtse** [comment]
@manuel489 can you also file an issue about Landscape on metanorma-standoc? Thanks!

**Comment by manuelfuenmayor** [comment]
> @manuel489 can you also file an issue about Landscape on metanorma-standoc? Thanks!

Ticket: https://github.com/metanorma/metanorma-standoc/issues/241

**Comment by ronaldtse** [comment]
Thanks @manuel489 !

**Pull request merged**
