### PR TITLE
actions-mn/build-and-publish#4 test implementation

### PR DESCRIPTION
**Pull request by CAMOBAP**
- actions-mn/build-and-publish#4

### CODE REVIEW

**Comment by CAMOBAP** [comment]
For some reason this approach simply doesn't work, i.e. `rossjrw/pr-preview-action` doesn't work as expected. Investigation in progress

**Comment by CAMOBAP** [comment]
@ronaldtse could you please doublecheck `Settings > Pages` and confirm that `Source` dropdown is set to `Deploy from ` branch` as described in https://github.com/rossjrw/pr-preview-action#usage

**Comment by ronaldtse** [comment]
@CAMOBAP I have updated the settings.

As per https://github.com/rossjrw/pr-preview-action/issues/21 , this GitHub action does not support the new "Deploy from Pages" option. This is likely because the new option depends on a whole replacement of the site, not backed by a Git repository which can be updated incrementally.

**Comment by ronaldtse** [comment]
Let's merge and see if it works.

**Pull request merged**
