### PR TITLE
actions-mn/build-and-publish#4 test preview pages deployment

### PR DESCRIPTION
**Pull request by CAMOBAP**
- actions-mn/build-and-publish#4

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@ronaldtse I wondering should we "downgrade" temporally and move to the old school GitHub Pages?

**Comment by ronaldtse** [comment]
@CAMOBAP we have already done that. How come I'm not seeing the new page?
Screenshot 2023-03-09 at 8 28 12 AM

There seems to only be pr-79, not pr-80, deployed.
Screenshot 2023-03-09 at 8 28 42 AM

**Comment by ronaldtse** [comment]
Also, https://metanorma.github.io/mn-samples-iho/pr-preview/pr-79 is also showing a 404.

**Comment by CAMOBAP** [comment]
1. The previous 79 PR is still there probably because while the merge new workflow `pull_request` with type `closed` wasn't fired

2. Also For some reason pages for this PR weren't committed due to permission issues

> ...
> /usr/bin/git push --porcelain ***github.com/metanorma/mn-samples-iho.git github-pages-deploy-action/ol3pqdksh:gh-pages
> remote: Permission to metanorma/mn-samples-iho.git denied to github-actions[bot].
> fatal: unable to access 'https://github.com/metanorma/mn-samples-iho.git/': The requested URL returned error: 403
> ...

Investigating

**Comment by CAMOBAP** [comment]
@ronaldtse maybe you have an idea where this workflow https://github.com/metanorma/mn-samples-iho/actions/workflows/pages/pages-build-deployment coming from and how to disable it ?

**Comment by ronaldtse** [comment]
@CAMOBAP that is the default GitHub pages workflow enabled by GitHub.

**Pull request merged**
