### PR TITLE
Add IHO S-5A

### PR DESCRIPTION
**Pull request by manuelfuenmayor**
As requested in https://github.com/metanorma/mn-samples-iho/issues/8

*Comments:*
- In this doc, I have typeset the first header of each table as a subsection. 

For example, consider capture: 

*Original:*
original-cap

*Code:*

 ````
== BASIC SUBJECTS

[[b1-mathematics-statistics-theory-of-observations]]
=== B1: Mathematics, statistics, theory of observations

[%unnumbered]
[cols="a,a,a"]
|===
h|Topic/Element h|Content h|Learning outcomes

3+h|B1.1 Geometry and Linear Algebra
...
````

*Generated:*
doc-cap

I did it on that way because, in the original source, those headers are referenced in the table of contents. So, I have encoded them as subsections in order for them to appear in the generated table of contents as well. (Let me know if I should discard this approach.)

Thanks!

### CODE REVIEW

**Review by ronaldtse — CHANGES_REQUESTED** [review]
@manuel489 there are many lines that have line breaks too short, e.g.

```
|H1.3c Kalman
filtering _(I)_
|
. Bayesian estimation
. State representation of a
dynamic observation equation,
observability
. Continuous, Semi-discrete and
discrete Kalman filtering
. Optimal smoothing
|Apply Kalman filtering methods to a
dynamic observation process.
```

But should be:
```
|H1.3c Kalman filtering _(I)_
|
. Bayesian estimation
. State representation of a dynamic observation equation, observability
. Continuous, Semi-discrete and discrete Kalman filtering
. Optimal smoothing
|Apply Kalman filtering methods to a dynamic observation process.
```

Please have fix all in 03 adoc (I've fixed all the rest). Thanks.

**Comment by manuelfuenmayor** [comment]
Ok @ronaldtse

**Comment by manuelfuenmayor** [comment]
Changes applied. Thanks!

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
Thanks @manuel489 !

**Pull request merged**
